### ISSUE TITLE
Running Totals always 0

### ISSUE THREAD

**Issue by slash-zero** [oliverlloyd/jmeter-ec2#26]
Hello,

During test runs, the running totals on the load controller are always 0.  If I SSH into one of the load generators, and tail the jmeter.log file, I do see the correct running totals.  @oliverlloyd, any idea what would be causing this?

Load Controller:
```
> 19:13:04: [RUNNING TOTALS] total count: 0, current avg: 0 (ms), average tps: 0 (p/sec), recent tps: 0 (p/sec), total errors: 0
```

jmeter.log on load generator:
```
2014/07/14 19:15:00 INFO  - jmeter.reporters.Summariser: summary +     13 in    14s =    0.9/s Avg:   136 Min:   117 Max:   188 Err:     0 (0.00%) Active: 1 Started: 1 Finished: 0
2014/07/14 19:15:00 INFO  - jmeter.reporters.Summariser: summary =    154 in   190s =    0.8/s Avg:   148 Min:    44 Max:   766 Err:     0 (0.00%)
```

**Comment by laukamp** [comment]
If your are running the example test, remove the schedule section to have running totals

**Comment by oliverlloyd** [comment]
I'm not able to reproduce this. Testing using the latest code and AMIs returns valid running total values.

**Comment by oliverlloyd** [comment]
Closing this for now. Seems to be an old issue.
