### ISSUE TITLE
s3/jmeter-ec2/JMeterPlugins.jar - AllAccessDisabled - All access to this object has been disabled

### ISSUE THREAD

**Issue by Lakhman** [oliverlloyd/jmeter-ec2#35]
Just tried running this script, was giving me errors, took me ages to debug but I think this is the issue:

https://s3.amazonaws.com/jmeter-ec2/JMeterPlugins.jar

    <?xml version="1.0" encoding="UTF-8"?>
    <Error>
        <Code>AllAccessDisabled</Code>
        <Message>All access to this object has been disabled</Message>
        <RequestId>74BA2D3C3841B0BD</RequestId>
        <HostId>e98OUXoHbq07QNr4kpBEsBIdjQONQCXSGveSDQ508X6q4oecj/eOFjxn2LbBzGTP</HostId>    
    </Error>

Can we have a mirror to this link or have it fixed please? - I tried installing another plugins.jar but kept getting errors with missing dependancies and such.

Thanks!

**Comment by oliverlloyd** [comment]
You're right that the link to this bucket is broken but can you help me, where did you find the link?

**Comment by Lakhman** [comment]
Yeah sure, here it is:

https://github.com/oliverlloyd/jmeter-ec2/blob/master/install.sh#L15

**Comment by oliverlloyd** [comment]
Thanks, just found it. 

So there's a problem with that bucket (basically it and a bunch of other stuff went and disappeared!). I've raised a ticket with Amazon about it and to solve the problem I've created a second location and updated the script but this won't help with anyone using the existing links - for that I have to wait for Amazon.

**Comment by Lakhman** [comment]
what? "just disappeared" - on S3? - (...quietly goes to backup everything on s3 to external hard drive)

People will update the script when they find it doesn't work!..

Awesome!
Thanks!! :)

**Comment by oliverlloyd** [comment]
Well, it got lost as part of a move between accounts, so it wasn't entirely random. Still annoying though.

Thanks for pointing out the problem.
Oliver

**Comment by Lakhman** [comment]
Ah ok! - Phew!

No Probs, Thanks for fixing it zippy quick! - And the awesome script! :+1:
