### ISSUE TITLE
the article link http://www.http503.com/2012/jmeter-ec2/ doesn't work any more

### ISSUE THREAD

**Issue by zhong88** [oliverlloyd/jmeter-ec2#38]
Hi, 
it would be nice if this article link http://www.http503.com/2012/jmeter-ec2/ could be updated. I'm new to was so this article would be really helpful for me to set up the environment.

Thanks!

**Comment by oliverlloyd** [comment]
Hmm, bit of a balls up I'm afraid. The db with those articles in is lost, utterly. Too many hosting providers, too many emails...

I found a cached version here though: http://web.archive.org/web/20120209090437/http://www.http503.com/2012/jmeter-ec2/ and most of the content is listed in the readme as part of this repo.

**Comment by oliverlloyd** [comment]
Fixed broken link using archived version.

https://github.com/oliverlloyd/jmeter-ec2/commit/7f9b1ad11289e251deb22f9959f806691f8e4389

**Comment by zhong88** [comment]
Thanks!
