### ISSUE TITLE
Load balancing in jmeter using master-slave technique 

### ISSUE THREAD

**Issue by Anjalipanwar** [oliverlloyd/jmeter-ec2#44]
Hi, I want to perform load test using master-slave. 

For Eg : 

I have 1 master and 10 slaves running and 1000 threads which are specified in master jmx file which should run in such a manner so that thread can be distributed among 10 slaves equally. 

Is there any way to modify jmx file in such a manner ? or any other alternatives ? 

Thanks !!

**Comment by oliverlloyd** [comment]
Yes, you can do this using this script. You should take a read through the readme.
