### ISSUE TITLE
Migrate to the latest CLI api

### ISSUE THREAD

**Issue by oliverlloyd** [oliverlloyd/jmeter-ec2#54]
Move from the [legacy tools](http://docs.aws.amazon.com/AWSEC2/latest/CommandLineReference/command-reference.html) that are currently being used to the [new api](http://docs.aws.amazon.com/cli/latest/reference/ec2/index.html).

**Comment by burnzy** [comment]
@oliverlloyd -- wondering if you've had a chance to start on this feature yet? Maybe I could help if not...

**Comment by oliverlloyd** [comment]
I haven't started and you're very welcome to have a go. This one is long overdue!

**Comment by burnzy** [comment]
Working on it!

**Comment by DineshShende** [comment]
+1

**Comment by oliverlloyd** [comment]
@burnzy Thanks loads for this.
