### ISSUE TITLE
--associate-public-ip-address does not accept "true" 

### ISSUE THREAD

**Issue by andrewlorien** [oliverlloyd/jmeter-ec2#70]
The first time i ran the script it did not create an instance, and returned 

> 
> Unknown options: "true"
> Amazon did not supply any instances, exiting

This was because the script has (in the subnet section)
` --associate-public-ip-address \"true\"`
instead of just
` --associate-public-ip-address `

**Comment by oliverlloyd** [comment]
Yup, this looks like a hangover from the EC2-VPC days that is causing issues now we're using the latest cli tools. I'll strip out the boolean in a bit.

Thanks for the report.

**Comment by gswallow** [comment]
I'm blocked because of this problem.  Could you do that sooner rather than later?

Thanks!
