### ISSUE TITLE
SCP verify.sh - PEM asks for Passphrase

### ISSUE THREAD

**Issue by gauravpatel2016** [oliverlloyd/jmeter-ec2#71]
Hi Oliver,

I am running your script on master EC2. For security reasons, our security group is set up to only accepts ssh on port 22 from internal IPs. However I noticed that "scp -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ............." command use public IP to SCP. What change i can make to use private ip (10.xx.xx.xx) instead of public?

Also I noticed if i change my security group to accept all inbound traffic from anywhere (unsafe), i noticed it asks for PassPhrase "Enter passphrase for key '/home/ubuntu/Documents/uswest2b.pem':" .... how do i resolve this?

Your help is appreciated.

Thanks,
Gv

**Comment by oliverlloyd** [comment]
To modify the script to use internal IPs you should look at this line: https://github.com/oliverlloyd/jmeter-ec2/blob/master/jmeter-ec2.sh#L325. I'd expect you can fairly easily modify this to return the private ip, not public one.

As for the passphrase, this isn't the script asking for a password, it's the instance that you are trying to ssh onto, there's nothing I can do about that. Usually this means your key isn't present on the box you're attempting to connect to, you are using the wrong username or you set a password when you generated this key. In any case, you might find this generic help text useful: https://github.com/oliverlloyd/jmeter-ec2#why-am-i-seeing-copying-installsh-to-1-serverslost-connection. Or just do a search for: 'Enter passphrase for key'.

**Comment by gauravpatel2016** [comment]
Thank you for quick reply. 
1) Private IP Address solution worked. Thanks so much
2) I regenerated keys and it worked as well.


**I am still getting "Lost Connection" on verify.sh [already checked your 'lost connection' section]**

scp -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no  -i /home/ubuntu/Documents/uswest2b.pem   -P 22  /home/ubuntu/Documents/jmeter-ec2/jmeter-ec2-master/verify.sh  /home/ubuntu/Documents/jmeter-ec2/jmeter-ec2-master/jmeter-ec2.properties                     ubuntu@[private_ip_address]:/home/ubuntu  && echo done > /home/ubuntu/Documents/jmeter-ec2/jmeter-ec2-master/1466731280-[private-ip]-scpverify.out

**Comment by gauravpatel2016** [comment]
OK so I fixed above issue by changing Jmeter version to 3.0. Hope this helps to someone
