### ISSUE TITLE
 Name or service not knownname 52.26.199.93

### ISSUE THREAD

**Issue by fdeamicis** [oliverlloyd/jmeter-ec2#73]
I'm trying to run the jMeter EC2 script on Cygwin64 which resides on a Windows 10 machine

I can start the jMeter script without problems

After the copying verify.sh to 1 server(s)... line, I always get 
OpenSSH_7.2p2, OpenSSL 1.0.2h  3 May 2016
" port 22esolving "52.26.199.93
: Name or service not knownname 52.26.199.93

I have put a -v parameter in the SCP call to get debug info.

If I open another Cygwin Window and telnet to the running service, I get a connection
If I open another Cygwin WIndow and SCP to the running service, I am also successful
If I open another Cygwin Window and do an ssh call, works like a charm

The SCP call on the jmeter-ec2.sh file fails

I've tried chmod 600 on the .pem file
I've tried user ubuntu
I've tried user ec-2
I've tried user root

No avail.

I'm hoping there is somebody out there with a similar situation because I'm so close to getting this script to work.  I just need someone to nudge me to the top of the mountain

![nameorservicenotknow](https://cloud.githubusercontent.com/assets/4235950/16636338/8292066e-43a5-11e6-875d-e95c834461f4.jpg)
![tellscp](https://cloud.githubusercontent.com/assets/4235950/16636352/8f2dd3b2-43a5-11e6-9f6e-6bc15c39c20a.jpg)
![ssh](https://cloud.githubusercontent.com/assets/4235950/16636543/c2f37002-43a6-11e6-92ac-d338cc839206.jpg)

If there's any other files I need to include with this ticket, let me know

**Comment by gauravpatel2016** [comment]
**1. Have you checked your /etc/hosts file?**

Should look like this

127.0.0.1	localhost
xx.xx.xx.xx [hostname]

===== 

**2. Also in jmeter-ec2.sh file, Line 427 add this and give me output**

p (scp -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no \
                    -i "$PEM_PATH/$PEM_FILE" \
                    -P $REMOTE_PORT \
                    $LOCAL_HOME/verify.sh \
                    $LOCAL_HOME/jmeter-ec2.properties \
                    $USER@$host:$REMOTE_HOME \
                    && echo "done" > $project_home/$DATETIME-$host-scpverify.out)


==================

Run step 2 command seperately on command line and fix it. Make sure Firewall is off

**Comment by fdeamicis** [comment]
My local host shows 
127.0.0.1       localhost

I noticed you put a p infront of (scp
What does that do.

**Comment by gauravpatel2016** [comment]
All it does is print the command it tries to execute.  have u tried
creating instance manually and scp to it ?i ran tgis script on ubuntu
machine and it created ubuntu vm and scp my jmx. not sure if something
needa to be done if you try to scp from ubuntu to win 10

**Comment by fdeamicis** [comment]
I'm wondering if the value of the $USER@$host:$REMOTE_HOME variable is being corrupted in any way

**Comment by fdeamicis** [comment]
Interesting finding.  When I hard code the $USER@$host:$REMOTE_HOME \ value in the jmeter-ec2.sh script while the instance is running, the SCP call goes through.  That makes me think there are two possibilities
     1.) The value of $USER@$host:$REMOTE_HOME is either getting formatted incorrectly
      2.) Once the instance status checks are complete, the SCP call is timing out

**Comment by fdeamicis** [comment]
The cause is the the value of $USER@$host:$REMOTE_HOME not getting formatted properly.  I'll have to debug and see how the hosts array is being formatted

**Comment by gauravpatel2016** [comment]
check your jmeter-ec2.properties file for USER variable. Set proper value there. Format of  $USER@$host:$REMOTE_HOME is correct.

**Comment by fdeamicis** [comment]
I had the jmeter-ec2.sh print out a list of the host ip it extracted from amazon which was 52.41.112.80

When I create a separate SCP call to the running instance and use ubuntu@52.41.112.80, the call works fine

When the jmeter-ec2.sh script makes the SCP call with ubuntu@52.41.112.80, we get an error

Either there is a space being inserted in the ip or the ip is correct and the user is mangled as mentioned by gauravpatel2016.  I'm getting closer to figuring this out

![host](https://cloud.githubusercontent.com/assets/4235950/16671759/5c56e7d8-446f-11e6-8ccc-071d694a5fb4.jpg)

![sc](https://cloud.githubusercontent.com/assets/4235950/16671768/65381c3c-446f-11e6-8f4d-4cc60a368e3e.jpg)

**Comment by gauravpatel2016** [comment]
What is permission of jmeter-ec2.sh

**Comment by gauravpatel2016** [comment]
I gave full write and read permission to my project directory

**Comment by fdeamicis** [comment]
I get a bad substitution error when I concatenate the strings.  That is the cause of all my issues. No sure how to fix
![badsub](https://cloud.githubusercontent.com/assets/4235950/16693310/ada80912-4502-11e6-84ef-86309dc3ea52.jpg)

**Comment by fdeamicis** [comment]
With $USER"@"$host":"$REMOTE_HOME,  the $host variable had a huge amount of leading spaces.  THat is why the  : ends up infront of the ubuntu@52.37.166.150

![v1](https://cloud.githubusercontent.com/assets/4235950/16748044/d7c42138-478f-11e6-9be6-bc88668ffe5e.jpg)

I had to add  "$(echo -e "${mystring}" | sed -e 's/[[:space:]]*$//')"   to the variable in order to get rid of the trailing spaces

![v3](https://cloud.githubusercontent.com/assets/4235950/16748127/63b03df8-4790-11e6-9187-3463e4401f47.jpg)
