### ISSUE TITLE
(standard_in) 2: syntax error (standard_in) 1: syntax error after waiting for test to start

### ISSUE THREAD

**Issue by fdeamicis** [oliverlloyd/jmeter-ec2#74]
This particular error comes after the line
 waiting for the test to start...to stop the test while it is running, press CTRL-C

The error is 
  (standard_in) 2: syntax error
  (standard_in) 1: syntax error

Should I even worry about this error.  It looks like the test ran properly

Has anyone ever encountered this error

![std](https://cloud.githubusercontent.com/assets/4235950/17119719/a2f3f0b2-5295-11e6-85ea-feda9594ef02.jpg)

**Comment by fdeamicis** [comment]
Resolved.  Some of the functions had a -n next to the echo.  I removed the -n

count_overallhosts=$(echo -n "$count_overallhosts+$count_total" | bc) # add the value from this host to the values from other hosts

**Comment by kimo23** [comment]
Hello fdeamicis,
didn't you had same issue like mine :  https://github.com/oliverlloyd/jmeter-ec2/issues/91
however my jmeter start many slaves but only frim one of them i get requests (threads) to my website, i don't know why i don't get from all of them : (
