### ISSUE TITLE
 Not authorized for images: [ami-caf501aa]

### ISSUE THREAD

**Issue by wzhonggo** [oliverlloyd/jmeter-ec2#78]
I want do test jmeter test in ec2  and  config like [this link](https://github.com/oliverlloyd/jmeter-ec2#setup) . I get error  **Not authorized for images: [ami-caf501aa]** when I run `count="1" /root/jmeter_aws/jmeter-ec2/jmeter-ec2.sh` . I not find this AMI**[ami-caf501aa]** in aws images . Anyone can help me.

![error](https://cloud.githubusercontent.com/assets/2763532/19219216/d9a0c212-8e3f-11e6-94ca-4754491cbcac.png)

![ami_not_found](https://cloud.githubusercontent.com/assets/2763532/19219207/ac55ef3a-8e3f-11e6-828a-b55cce91e8ac.png)

**Comment by oliverlloyd** [comment]
Thanks. Some of the listed example AMIs were set to Private for some reason. I've set the to Public so that command should work now.

**Comment by wzhonggo** [comment]
It is can create instance from **[ami-caf501aa]** .  Thank you very much.
