### ISSUE TITLE
Unable to execute my test with this project

### ISSUE THREAD

**Issue by ravibabu101143** [oliverlloyd/jmeter-ec2#81]
Hi,

I have cloned the project and have followed all your instructions and when tried to run  using the following command, got the error 
 "'count' is not recognized as an internal or external command,
operable program or batch file."

Tried with below options:
I was in my project folder "D:\forcloud\loadtest" and ran the following command:
count="1" D:\\forcloud\\loadtest\\jmeter-ec2-master\\jmeter-ec2.sh

Another option i have tried is 
count="1" ./meter-ec2-master/jmeter-ec2.sh

Any help is greatly appreciated!!

**Comment by oliverlloyd** [comment]
Are you using windows?

**Comment by ravibabu101143** [comment]
Yes Windows 2012 server

**Comment by oliverlloyd** [comment]
I'm afraid Windows is not explicitly supported. I think you can make it work using Cygwin or similar, I know others have done this, but it's not something I can promise.

**Comment by ravibabu101143** [comment]
Thanks for the update. Appreciate your quick response.
