### ISSUE TITLE
Error on floating point arithmetic

### ISSUE THREAD

**Issue by abhi92** [oliverlloyd/jmeter-ec2#83]
./jmeter-ec2.sh: line 81: 0 + 3.6: syntax error: invalid arithmetic operator (error token is ".6")
Bash doesn't understand floating pt arithmetic.

**Comment by benztest** [comment]
I've received the same issue as well. 

Line 81 points to `echo $[$1 + $2]` in the jmeter-ec2.sh file

I've temporarily replaced the lines that use 'add' to an older release. (example)
`#count_overallhosts=$(add $count_overallhosts $count_total)`
to
'count_overallhosts=$(echo "$count_overallhosts+$count_total" | bc)'

This bypasses the error report in console when executing.

**Comment by abhi92** [comment]
Yeah.. I had changed the add function itself to use bc

**Comment by oliverlloyd** [comment]
This sound like a regression bug. I knew there was a reason I'd used `bc`... @benztest Do you want to put that fix into a pull request and I'll merge it in. I think it would still be good to keep the `add` function though, for neatness.

**Comment by benztest** [comment]
@oliverlloyd sure, I'll give it ago.

**Comment by oliverlloyd** [comment]
Closed by PR #84
