### ISSUE TITLE
Unable execute ec2-jmeter 

### ISSUE THREAD

**Issue by DineshShende** [oliverlloyd/jmeter-ec2#85]
When i run following command
count="1" /home/ubuntu/ec2-jmeter/jmeter-ec2-master/jmeter-ec2.sh

Console hangs after starting test and is not executing the jmeter script,it was working fine in last week

Console Log as follows:
(Note: No jmeter log file found on ec2 instance)

-------------------------------------------------------------------------------------
       jmeter-ec2 Automation Script - Running CompleteRegister.jmx over 1 predefined host(s)
   -------------------------------------------------------------------------------------

copying verify.sh to 1 server(s)...
[##################################################] 100.00% - (1 of 1)  - Done.

running verify.sh on 1 server(s)...
[##################################################] 100.00% - (1 of 1)  - Done.

editing thread counts...

 - CompleteRegister.jmx has 1 threadgroup(s) - [inc. those disabled]
 - There are 3 threads in the test plan, this test is set to execute 100 percent of these, so will run using 3 threads

thread counts updated

copying test files to 1 server(s)...jmx files..done....data dir..done....jmeter.properties..done....jmeter execution file...done....project specific jar file(s)...done....all files uploaded

starting jmeter on:
ec2-XX-XXX-XXX-XXX.compute-1.amazonaws.com

JMeter started at Sat Nov  5 12:07:10 IST 2016
===================================================================== START OF JMETER-EC2 TEST ================================================================================
> [updates: every 15 seconds | running total: every 45 seconds]
>
> waiting for the test to start...to stop the test while it is running, press CTRL-C

**Comment by DineshShende** [comment]
Update:Works fine with ami-c8580bdf(Ubuntu 14.04) but failed for ami-40d28157(Ubuntu 16.04)

**Comment by oliverlloyd** [comment]
A couple of things. You appear to be using a predefined host so the AMI will have no direct effect. But assuming you're talking about the AMI you use to build the server(s) you enter into `REMOTE_HOSTS`, then I'd recommend sticking with the AMIs listed in the `jmeter.properties` file, these have the required software (at the correct versions) present. Anything outside of these is 'at your own risk' so to speak.
