### ISSUE TITLE
Some errors when executing the script

### ISSUE THREAD

**Issue by nvingenieria** [oliverlloyd/jmeter-ec2#88]
Hi, 

When I run the script I get some errors and then it hangs at "waiting for the test to start"
We are using AMI ami-ae72f2dd.

Any ideas?

Thanks,
Daniel

   -------------------------------------------------------------------------------------
       jmeter-ec2 Automation Script - Running bimba.jmx over 1 AWS Instance(s)
   -------------------------------------------------------------------------------------

Requesting 1 instance(s)...success

waiting for instance status checks to pass (this can take several minutes)...
(standard_in) 1: syntax error
[                                                  ] 0,00% - (0 of 1) - (standard_in) 1: syntax error
[                                                  ] 0,00% - (0 of 1) \ (standard_in) 1: syntax error
[                                                  ] 0,00% - (0 of 1) | (standard_in) 1: syntax error
[                                                  ] 0,00% - (0 of 1) / (standard_in) 1: syntax error
. . . . . 
[                                                  ] 0,00% - (0 of 1) \ (standard_in) 1: syntax error
[                                                  ] 0,00% - (0 of 1) | (standard_in) 1: syntax error
[                                                  ] 0,00% - (0 of 1) / jmeter-ec2.sh: línea 984: printf: 50.00000000000000000000: número inválido
jmeter-ec2.sh: línea 992: printf: 100.00000000000000000000: número inválido
(standard_in) 1: syntax error
[                                                  ] 0,00% - (1 of 1)  - Done.

assigning tags...
complete

copying verify.sh to 1 server(s)...
(standard_in) 1: syntax error
[                                                  ] 0,00% - (0 of 1) - (standard_in) 1: syntax error
[                                                  ] 0,00% - (0 of 1) \ (standard_in) 1: syntax error
[                                                  ] 0,00% - (0 of 1) | (standard_in) 1: syntax error
[                                                  ] 0,00% - (0 of 1) / jmeter-ec2.sh: línea 984: printf: 50.00000000000000000000: número inválido
jmeter-ec2.sh: línea 992: printf: 100.00000000000000000000: número inválido
(standard_in) 1: syntax error
[                                                  ] 0,00% - (1 of 1)  - Done.

running verify.sh on 1 server(s)...
(standard_in) 1: syntax error
[                                                  ] 0,00% - (0 of 1) - (standard_in) 1: syntax error
[                                                  ] 0,00% - (0 of 1) \ jmeter-ec2.sh: línea 984: printf: 50.00000000000000000000: número inválido
jmeter-ec2.sh: línea 992: printf: 100.00000000000000000000: número inválido
(standard_in) 1: syntax error
[                                                  ] 0,00% - (1 of 1)  - Done.

editing thread counts...

 - bimba.jmx has 2 threadgroup(s) - [inc. those disabled]
 - Thread group compra has 0 threads, 100 percent of this is 0 which rounds to 0, so we're going to set it to 1 instead.
 - There are 10 threads in the test plan, this test is set to execute 100 percent of these, so will run using 12 threads

thread counts updated

copying test files to 1 server(s)...jmx files..done....data dir..done....jmeter.properties..done....system.properties..done....jmeter execution file...done....custom jar file(s)...done....project specific jar file(s)...done....all files uploaded

starting jmeter on:
54.154.184.174

JMeter started at dom mar 12 11:36:47 UTC 2017
====================== START OF JMETER-EC2 TEST =================================
> [updates: every 15 seconds | running total: every 45 seconds]
>
> waiting for the test to start...to stop the test while it is running, press CTRL-C

**Comment by joeboyscout04** [comment]
I am getting the same behavior as well.

**Comment by joeboyscout04** [comment]
I was using Jmeter 3.1, when I edited the jmeter-ec2.properties file to include 

JMETER_VERSION="apache-jmeter-3.1"

Then the test no longer hangs.

**Comment by sj82516** [comment]
I have same issue. @joeboyscout04 's solution is worked.
Thanks a lot.
